// Mocks generated by Mockito 5.4.0 from annotations
// in marvel/test/presentation/controller/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:marvel/domain/entity/character_list.dart' as _i5;
import 'package:marvel/domain/usecase/fetch_characters_usecase.dart' as _i6;
import 'package:marvel/domain/usecase/fetch_random_char_usecase.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchRandomCharactersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class fetchRandom extends _i1.Mock implements _i3.FetchRandomCharactersUseCase {
  @override
  _i4.Future<_i2.Either<Exception, _i5.CharacterList>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<Exception, _i5.CharacterList>>.value(
            _FakeEither_0<Exception, _i5.CharacterList>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<Exception, _i5.CharacterList>>.value(
                _FakeEither_0<Exception, _i5.CharacterList>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<Exception, _i5.CharacterList>>);
}

/// A class which mocks [FetchCharactersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class fetchAll extends _i1.Mock implements _i6.FetchCharactersUseCase {
  @override
  _i4.Future<_i2.Either<Exception, _i5.CharacterList>> execute(
          {int? lastIndex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#lastIndex: lastIndex},
        ),
        returnValue: _i4.Future<_i2.Either<Exception, _i5.CharacterList>>.value(
            _FakeEither_0<Exception, _i5.CharacterList>(
          this,
          Invocation.method(
            #execute,
            [],
            {#lastIndex: lastIndex},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<Exception, _i5.CharacterList>>.value(
                _FakeEither_0<Exception, _i5.CharacterList>(
          this,
          Invocation.method(
            #execute,
            [],
            {#lastIndex: lastIndex},
          ),
        )),
      ) as _i4.Future<_i2.Either<Exception, _i5.CharacterList>>);
}
